# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-04 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yyname', models.CharField(max_length=20)),
                ('regurl', models.CharField(max_length=80)),
                ('logdir', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': '\u8def\u5f84\u4fe1\u606f',
                'verbose_name_plural': '\u8bb0\u5f55\u5e94\u7528\u540d\u5b57\u65e5\u5fd7\u8def\u5f84\u7b49',
            },
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.CharField(max_length=30)),
                ('yy', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '\u5e94\u7528Ip',
                'verbose_name_plural': '\u8bb0\u5f55\u5e94\u7528\u6570\u636e\u5e93\u4e0eIp\u5730\u5740',
            },
        ),
    ]
