# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-04 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190304_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.CharField(max_length=30)),
                ('yy', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '\u5e94\u7528Ip',
                'verbose_name_plural': '\u8bb0\u5f55\u5e94\u7528\u6570\u636e\u5e93\u4e0eIp\u5730\u5740',
            },
        ),
    ]
