# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-04 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ip',
            options={},
        ),
    ]
