# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-04 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190304_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IP',
            new_name='IPAAA',
        ),
    ]
