# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-04 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190304_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipaaa',
            old_name='db',
            new_name='aaa',
        ),
        migrations.RenameField(
            model_name='ipaaa',
            old_name='yy',
            new_name='bbb',
        ),
    ]
