# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-04 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190304_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaaa',
            options={'verbose_name': '\u5e94\u7528Ip', 'verbose_name_plural': '\u8bb0\u5f55\u5e94\u7528\u6570\u636e\u5e93\u4e0eIp\u5730\u5740'},
        ),
    ]
